# Generated by Django 4.2.30 on 2026-08-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='low_stock_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='maintenance_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='overdue_allocation_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
