# Generated by Django 4.2.30 on 2026-08-28 09:16

from django.db import migrations, models


def set_existing_profiles_to_approved(apps, schema_editor):
    Profile = apps.get_model('assets', 'Profile')
    Profile.objects.all().update(account_status='APPROVED')

def reverse_set_existing_profiles(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_profile_role_alter_allocation_id_alter_asset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISABLED', 'Disabled')], default='PENDING', max_length=20),
        ),
        migrations.RunPython(set_existing_profiles_to_approved, reverse_set_existing_profiles),
    ]
