# Generated by Django 4.2.30 on 2026-09-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_profile_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Administrator'), ('TECHNICIAN', 'Technician'), ('NORMAL_USER', 'Normal User')], default='NORMAL_USER', max_length=30),
        ),
    ]
