# Generated by Django 4.2.30 on 2026-09-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='allocation_type',
            field=models.CharField(choices=[('FULL', 'Full Allocation'), ('PARTIAL', 'Partial Allocation'), ('PERMANENT', 'Permanent Allocation')], default='PERMANENT', max_length=20),
        ),
        migrations.AddField(
            model_name='allocation',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
